<a href="https://colab.research.google.com/github/e-upho/Programaci-n-Aplicada/blob/main/Corte%202/Numpy/Ejercicios_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np# Importa la librería NumPy, esencial para operaciones numéricas avanzadas.

sample_list = [1, 2, 3]# Define una lista simple de Python.

np.array(sample_list)# Convierte la lista de Python en un array de NumPy.

array([1, 2, 3])

In [ ]:
my_vector = np.array(['this', 'is', 'a', 'vector'])# Crea un array de NumPy con elementos de tipo cadena (texto).
print(my_vector)

['this' 'is' 'a' 'vector']


In [ ]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]# Define una matriz como una lista anidada de Python.

np.array(my_matrix)# Convierte la lista anidada en una matriz (array bidimensional) de NumPy.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,5)# Crea un array con números enteros desde 0 hasta 4 (excluyendo el 5).

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,11,2)
# Crea un array con números impares desde 1 hasta 10, con un paso de 2.

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(4)# Crea un array de 4 ceros.

array([0., 0., 0., 0.])

In [ ]:
np.ones(5)# Crea un array de 5 unos.

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0, 1, 10)# Crea un array con 10 números espaciados uniformemente entre 0 y 1.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.eye(1)# Crea una matriz identidad de tamaño 1x1.

np.eye(2)# Crea una matriz identidad de tamaño 2x2.

np.eye(50)# Crea una matriz identidad de tamaño 50x50.

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
size = 5           # Tamaño del array
low, high = 1, 10  # Límites para enteros

np.random.randint(0, 10, sample_size)  # Genera 5 números enteros entre 0 (inclusive) y 10 (exclusive)

np.random.rand(sample_size)# Genera un array de números aleatorios con distribución uniforme entre 0 y 1.



np.random.randn(sample_size)# Genera un array de números aleatorios con distribución normal estándar (media 0, desviación estándar 1).


np.random.randint(low, high, sample_size)# 'low', 'high', y 'sample_size' deben ser definidos previamente, por ejemplo: low=0, high=10, sample_size=5

array([6, 6, 7, 6, 9])

In [ ]:
arr = np.array([0,1,2,3,4,5])# Define un array unidimensional.
arr.reshape(2,3)# Remodela el array a una matriz de 2 filas y 3 columnas.

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.array([0,1,2,3,4,5])
# Define un array unidimensional.

arr.shape# Muestra la forma (dimensiones) actual del array.

arr = arr.reshape(2,3)# Remodela el array a una matriz de 2 filas y 3 columnas.

arr.shape# Muestra la nueva forma del array después de ser remodelado.

(2, 3)

In [ ]:
arr.reshape(2,3).shape # Remodela el array temporalmente y luego muestra la forma resultante.

(2, 3)

In [ ]:
simple_array = [1, 2, 3, 4]# Define un array simple (nota: esto es una lista, no un array de NumPy).

In [ ]:

# Encuentra el valor máximo en el array.
# (Nota: 'simple_array' es una lista, para usar .max() con NumPy, debería ser un np.array)
# Por ejemplo: np.array(simple_array).max()
simple_array = np.array([3, 1, 4, 2, 5])
maximo = simple_array.max()

In [ ]:
simple_array.argmax()# Encuentra el índice del valor máximo en el array.

np.int64(4)

In [ ]:
simple_array.min()# Encuentra el valor mínimo en el array.

simple_array.argmin()# Encuentra el índice del valor mínimo en el array.

np.int64(1)

In [ ]:
arr = np.arange(4)# Crea un array con números enteros de 0 a 3.
arr# Muestra el array.

array([0, 1, 2, 3])

In [ ]:
2 + arr# Suma 2 a cada elemento del array.

array([2, 3, 4, 5])

In [ ]:
arr + arr# Suma cada elemento del array consigo mismo.

array([0, 2, 4, 6])

In [ ]:
arr - 10# Resta 10 a cada elemento del array.

arr - arr# Resta cada elemento del array consigo mismo (resultando en ceros).

array([0, 0, 0, 0])

In [ ]:
6 * arr# Multiplica cada elemento del array por 6.

arr * arr# Multiplica cada elemento del array por sí mismo.

array([0, 1, 4, 9])

In [ ]:
arr / 2# Divide cada elemento del array por 2.

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

In [ ]:
arr / arr# Divide cada elemento del array por sí mismo (división por cero para el primer elemento).

<ipython-input-77-4211002065>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr# Divide cada elemento del array por sí mismo (división por cero para el primer elemento).


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.]])

In [ ]:
np.sqrt(arr)# Calcula la raíz cuadrada de cada elemento del array.

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.exp(arr)# Calcula la exponencial de cada elemento del array.

np.sin(arr)# Calcula el seno de cada elemento del array.

np.cos(arr)# Calcula el coseno de cada elemento del array.

np.log(arr)# Calcula el logaritmo natural de cada elemento del array.

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
arr = np.random.rand(5)# Crea un array de 5 números aleatorios con distribución uniforme entre 0 y 1.
arr

array([0.55522686, 0.70449506, 0.75658866, 0.93416041, 0.34440429])

In [ ]:
arr = np.round(arr, 2)# Redondea cada elemento del array a 2 decimales.

In [ ]:
arr[0]# Accede al primer elemento del array (índice 0).

np.float64(0.56)

In [ ]:

arr[:]# Selecciona todos los elementos del array.

arr[1:]# Selecciona todos los elementos desde el índice 1 hasta el final.

arr[1:4]# Selecciona los elementos desde el índice 1 hasta el índice 3 (excluido el 4).

array([0.7 , 0.76, 0.93])

In [ ]:
arr[:] = 0# Asigna el valor 0 a todos los elementos del array.

arr# Muestra el array modificado.

array([0., 0., 0., 0., 0.])

In [ ]:
arr[2:5] = 0.5# Asigna el valor 0.5 a los elementos desde el índice 2 hasta el 4 (excluido el 5).

arr# Muestra el array modificado.

array([0.56, 0.7 , 0.5 , 0.5 , 0.5 ])

In [ ]:

new_array = np.array([6, 7, 8, 9])# Define un nuevo array de NumPy.

second_new_array = new_array[0:2]# Crea una vista del 'new_array', los cambios en 'second_new_array' afectarán a 'new_array'.

second_new_array# Muestra la vista.

array([6, 7])

In [ ]:
second_new_array[1] = 4# Modifica un elemento en la vista 'second_new_array'.

second_new_array# Muestra la vista modificada.

array([6, 4])

In [ ]:
new_array# Muestra el 'new_array' original para ver el efecto del cambio en la vista.

array([6, 4, 8, 9])

In [ ]:
array_to_copy = np.array([1, 2, 3])# Define un array para copiar.

copied_array = array_to_copy.copy()# Crea una copia independiente del array.

array_to_copy# Muestra el array original.

copied_array# Muestra el array copiado.

array([1, 2, 3])

In [ ]:
copied_array[0] = 9# Modifica el primer elemento del array copiado.

copied_array# Muestra el array copiado modificado.

array_to_copy# Muestra el array original (permanece sin cambios).

array([1, 2, 3])

In [ ]:
mat = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])# Define una matriz (array bidimensional).
mat# Muestra la matriz.

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
mat[0]# Accede a la primera fila de la matriz (índice 0).
mat[0][-1]# Accede al último elemento de la primera fila.

np.int64(15)

In [ ]:
mat[1:][:2]# Selecciona las filas desde la segunda (índice 1) hasta el final, y luego las dos primeras de esas filas seleccionadas.

array([[20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])# Define un array de NumPy.

arr > 0.7# Realiza una comparación booleana, devolviendo un array de True/False.

array([False,  True, False,  True,  True])

In [ ]:
arr[arr > 0.7]# Usa el array booleano para seleccionar solo los elementos donde la condición es True.

array([0.94, 0.73, 0.83])